@startuml
left to right direction

actor Usuário as user

rectangle "Realizar Compra Online" {

  user --> (Autenticar no Sistema)
  user --> (Adicionar Itens ao Carrinho)
  user --> (Prosseguir com a Compra)
  user -- (Fornecer Informações de Pagamento)
  user --> (Revisar a Compra) 
  (Prosseguir com a Compra) . (Fornecer Informações de Pagamento)
  (Fornecer Informações de Pagamento) -- (Validar Informações de Pagamento) 
  (Validar Informações de Pagamento) --> (Confirmação de Compra)
  (Confirmação de Compra) --> (Enviar E-mail de Confirmação)
  (Enviar E-mail de Confirmação) --> user
}

@enduml
