@startuml

    left to right direction

    actor "Gerente de compras" as gc
    actor "Suprevisor(a) de estoque" as se 
    actor "Coordenador de produção" as cp 
    actor "Analista de qualidade" as aq
    actor "Responsável por vendas" as rv

rectangle "Caso de uso"{
    aq -- (Monitorar produção)
    aq -- (Realizar inspeções)
    gc --> se
    gc -- (Adquirir ingredientes)
    se -- (Gerenciar armazenamento)
    se -- (Organizar materiais)
    gc -- (Realizar pedidos)
    gc -- (Negociar preços)
    cp -- (Planejar produção)
    cp -- (Utilizar materiais)
    rv -- (Coordenar entregas)
    rv -- (Registrar vendas)
}

@enduml